"""migrating

Revision ID: 948b7b6f3a22
Revises: 9314372039b1
Create Date: 2018-09-19 14:51:13.815551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948b7b6f3a22'
down_revision = '9314372039b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
